### ISSUE TITLE
Group id does not start with -100

### ISSUE THREAD

**Issue by SJ50** [shrey2199/LD_Meta_bot#1]
Hi, 
I got group id with does not start with -100 but starts with -490xxxxxx.
I even try using -100490xxxxxx but this does not work.
because of this I keep getting error 
"Error :  You are not Authorized to access the bot. Pls Add Chat ID to Config Vars."

**Comment by ghost** [comment]
Make it Supergroup means public group

**Comment by SJ50** [comment]
I toggle chat history to make group supergroup.
